import {useEffect,useState} from 'react'
import {ArrowRight,BarChart3,Briefcase,CheckSquare,ChevronRight,FileText,LayoutDashboard,LogOut,Menu,MessageSquare,Users,X} from 'lucide-react'
import {erpApi} from './erpApi'
const nav=[['dashboard','Dashboard',LayoutDashboard],['enquiries','Enquiries',MessageSquare],['clients','Clients',Users],['engagements','Engagements',Briefcase],['tasks','Tasks',CheckSquare],['documents','Documents',FileText]]
function BrandLockup(){return <div className="erp-brand-lockup"><img src={`${import.meta.env.BASE_URL}logo/Brainbanque-logo%20without%20BG.jpg`} alt="BrainBanque Global Solutions"/><span><strong><i>Brain</i><b>Banque</b></strong><small>Global Solutions (P) Ltd</small></span></div>}
function Login({onLogin,onAdmin}){const [email,setEmail]=useState(''),[name,setName]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('')
async function submit(e){e.preventDefault();setLoading(true);setError('');try{const x=await erpApi.login(email,name);onLogin(x)}catch(e){setError(e.message)}finally{setLoading(false)}}
return <div className="erp-login"><div className="login-card"><BrandLockup/><p className="eyebrow">PRIVATE WORKSPACE</p><h1>Welcome back.</h1><p>Sign in to the BrainBanque management workspace.</p><form onSubmit={submit}><label>Name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><label>Work email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label>{error&&<div className="erp-error">{error}</div>}<button className="button primary full" disabled={loading}>{loading?'Signing in…':'Continue'}<ChevronRight size={17}/></button></form><a className="admin-login-link" href="#/erp-admin">Admin Login <ArrowRight size={14}/></a><small>Access is controlled by the BrainBanque Apps Script backend.</small></div></div>}
function AdminLogin({onLogin}){const [password,setPassword]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('')
async function submit(e){e.preventDefault();setLoading(true);setError('');try{const x=await erpApi.adminLogin(password);onLogin(x)}catch(e){setError(e.message)}finally{setLoading(false)}}
return <div className="erp-login admin-login-screen"><div className="login-card"><BrandLockup/><p className="eyebrow">ADMINISTRATOR ACCESS</p><h1>Admin Login.</h1><p>Enter the administrator password to access the BrainBanque management workspace.</p><form onSubmit={submit}><label>Administrator password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password" autoFocus/></label>{error&&<div className="erp-error">{error}</div>}<button className="button primary full" disabled={loading}>{loading?'Verifying…':'Enter Admin Workspace'}<ArrowRight size={17}/></button></form><a className="admin-back-link" href="#/erp">← Back to normal login</a><small>Administrator access is validated by the BrainBanque backend.</small></div></div>}

function ERP({session,onLogout}){const [page,setPage]=useState('dashboard'),[open,setOpen]=useState(false),[data,setData]=useState({}),[loading,setLoading]=useState(false),[error,setError]=useState('')
const load=async p=>{setPage(p);setOpen(false);if(p==='dashboard')return;setLoading(true);setError('');try{const entity=p==='enquiries'?'enquiries':p;setData({...data,[p]:await erpApi.list(entity,session.token)})}catch(e){setError(e.message)}finally{setLoading(false)}}
useEffect(()=>{load('enquiries')},[])
const rows=data[page]||[]
return <div className="erp"><aside className={open?'erp-side open':'erp-side'}><div className="erp-logo brand"><span className="brand-mark">B</span><span>brainbanque</span></div><div className="erp-label">WORKSPACE</div>{nav.map(([id,label,Icon])=><button className={page===id?'active':''} key={id} onClick={()=>load(id)}><Icon size={17}/>{label}</button>)}<div className="erp-side-bottom"><div><b>{session.user.name}</b><small>{session.user.role}</small></div><button onClick={onLogout}><LogOut size={17}/> Sign out</button></div></aside><main className="erp-main"><header className="erp-header"><button className="erp-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><p className="eyebrow">BRAINBANQUE / MANAGEMENT</p><h2>{nav.find(x=>x[0]===page)?.[1]||'Dashboard'}</h2></div><div className="erp-user">{session.user.name}<span>{session.user.role}</span></div></header>{page==='dashboard'?<Dashboard data={data}/>:<TablePage title={nav.find(x=>x[0]===page)?.[1]} rows={rows} loading={loading} error={error}/>}</main></div>}
function Dashboard({data}){return <div className="erp-content"><div className="dash-welcome"><div><p className="eyebrow">OVERVIEW</p><h1>Good day, {sessionName()}.</h1><p>Your operational workspace for client work and professional engagements.</p></div><div className="dash-icon"><BarChart3/></div></div><div className="metrics">{[['Clients','clients'],['Enquiries','enquiries'],['Engagements','engagements'],['Tasks','tasks']].map(([x,k])=><div className="metric" key={k}><span>{x}</span><strong>{(data[k]||[]).length}</strong><small>Current records</small></div>)}</div><div className="panel"><div><p className="eyebrow">OPERATING MODEL</p><h3>One workspace for the work behind the business.</h3></div><div className="panel-points"><span>Client management</span><span>Engagement delivery</span><span>Task coordination</span><span>Document control</span></div></div></div>}
let currentName='Team member'; function sessionName(){return currentName}
function TablePage({title,rows,loading,error}){return <div className="erp-content"><div className="table-head"><div><p className="eyebrow">RECORDS</p><h1>{title}</h1></div><button className="button primary">+ New {title?.slice(0,-1)}</button></div>{error&&<div className="erp-error">{error}</div>}<div className="data-panel">{loading?<div className="empty">Loading…</div>:rows.length?<div className="table-wrap"><table><thead><tr>{Object.keys(rows[0]).slice(0,6).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{Object.keys(rows[0]).slice(0,6).map(k=><td key={k}>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div>:<div className="empty">No {title?.toLowerCase()} yet.</div>}</div></div>}
export default function ERPApp({adminMode=false}){const [session,setSession]=useState(()=>{try{return JSON.parse(localStorage.getItem('bb_session'))}catch{return null}});if(session)currentName=session.user.name;const logout=async()=>{try{await erpApi.logout(session.token)}catch{}localStorage.removeItem('bb_session');setSession(null)};if(!session)return adminMode?<AdminLogin onLogin={x=>{localStorage.setItem('bb_session',JSON.stringify(x));setSession(x)}}/>:<Login onLogin={x=>{localStorage.setItem('bb_session',JSON.stringify(x));setSession(x)}}/>;return <ERP session={session} onLogout={logout}/>}
